First attempt
Particular/NServiceBus pull request #5766
Opened 2020-09-25 06:46 UTC by aleksandr-samila

2020-09-29 08:03 UTC, andreasohlund requested changes

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core.Tests/Unicast/LoadHandlersBehaviorTests.cs
> +            //var behavior = new LoadHandlersConnector(new MessageHandlerRegistry(), new InMemorySynchronizedStorage(), new InMemoryTransactionalSynchronizedStorageAdapter());
Just create a fake InMemorySynchronizedStorage in this class and use that one

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxSettingsExtensions.cs
> +    [ObsoleteEx(Message = "!!!", TreatAsErrorFromVersion = "8.0.0", RemoveInVersion = "9.0.0")]
Move this class to obsoletes.cs

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxPersistence.cs
> +    public class InMemoryOutboxPersistence
Move this class to obsoletes.cs

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersistence.cs
> +    public class InMemorySagaPersistence
Move this class to obsoletes.cs

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionPersistence.cs
> +    public class InMemorySubscriptionPersistence
Move this class to obsoletes.cs

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersistence.cs
> +    public class InMemoryTimeoutPersistence
Move this class to obsoletes.cs

2020-09-29 08:03 UTC, andreasohlund commented on src/NServiceBus.Core/Persistence/InMemory/InMemory.cs
> +    public class InMemoryPersistence
Move this class to obsoletes.cs

2020-10-14 06:47 UTC, closed without merging

2021-01-25 16:37 UTC, adamralph commented
@lailabougria can we delete the branch?

2021-01-26 07:30 UTC, lailabougria commented
@adamralph Done!