Introduced Acceptance Testing Persistence
Particular/NServiceBus pull request #5781
Opened 2020-10-07 08:40 UTC by aleksandr-samila

Initialization.
Will be used as a base instead of InMemory persistence for tests

2020-10-08 08:45 UTC, andreasohlund requested changes
Nice work. only thing left to do is to make sure that all tests in `NServiceBus.AcceptanceTests that currently use the `InMemoryPersitence` is changed to use the new persister. 

Code File Line Column Project Kind Containing Member Containing Type
configuration.UsePersistence<InMemoryPersistence>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\ConfigureEndpointInMemoryPersistence.cs 9 38 NServiceBus.AcceptanceTests (net472) Type Argument Configure ConfigureEndpointInMemoryPersistence
c.UsePersistence<InMemoryPersistence, StorageType.Sagas>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_outbox.cs 27 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Timeouts>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_outbox.cs 28 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Subscriptions>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_outbox.cs 29 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Timeouts>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_saga.cs 29 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Outbox>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_saga.cs 30 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Subscriptions>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_saga.cs 31 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Sagas>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_subscriptions.cs 28 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Outbox>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_subscriptions.cs 29 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Timeouts>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_subscriptions.cs 30 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Sagas>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_timeouts.cs 30 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Outbox>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_timeouts.cs 31 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence, StorageType.Subscriptions>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Persistence\When_a_persistence_does_not_support_timeouts.cs 32 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor Endpoint
c.UsePersistence<InMemoryPersistence>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Sagas\When_adding_state_to_context.cs 43 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor SagaEndpoint
c.UsePersistence<InMemoryPersistence>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Sagas\When_finder_cant_find_saga_instance.cs 40 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor SagaEndpoint
config.UsePersistence<InMemoryPersistence>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Sagas\When_overriding_saga_id_creation.cs 43 43 NServiceBus.AcceptanceTests (net472) Type Argument .ctor EndpointThatHostsASaga
c.UsePersistence<InMemoryPersistence, StorageType.Subscriptions>(); C:\Users\andre\Documents\GitHub\NServiceBus\src\NServiceBus.AcceptanceTests\Core\Sagas\When_saga_scanned_send_only_and_no_saga_storage.cs 29 38 NServiceBus.AcceptanceTests (net472) Type Argument .ctor SendOnlyEndpointWithSaga

2020-10-08 08:45 UTC, andreasohlund commented on src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/AcceptanceTestingPersistence.cs
> +    class AcceptanceTestingPersistence : PersistenceDefinition
This needs to be public so that downstreams can use it

2020-10-08 12:42 UTC, aleksandr-samila commented
Required changes were made.
Tests are green

2020-10-08 12:53 UTC, lailabougria approved these changes

2020-10-09 11:18 UTC, andreasohlund approved these changes
Made a few tweaks, should be good to go

2020-10-09 11:31 UTC, merged