Add a test for disabled autosubscribe behavior
Particular/NServiceBus pull request #5879
Opened 2021-01-26 09:10 UTC by timbussmann

Test that when disabling autosubscribe, no events are automatically subscribed, regardless if the transport uses native or message driven pubsub. This ensures that the "disable autosubscribe" configuration is respected in both cases.

There need to be two test cases because of the slightly different setup requirements for subscriptions and the delayed nature of message driven pub-sub

2021-01-26 09:29 UTC, SzymonPobiega approved these changes

2021-01-27 08:04 UTC, tmasternak requested changes

2021-01-27 08:04 UTC, tmasternak commented on src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_autosubscribe_disabled.cs
> +            Assert.IsFalse(context.NonSubscribedEventReceived);
This assertion can give false positives when `ManuallySubscribedEventReceived` and `NonSubscribedEventReceived` are both subscribed to but `NonSubscribedEventReceived` happens to be received first.
Could we make the test more predictable by testing if the `Subscribe` operations are called or not for the events by the `AutoSubscribe` feature?

2021-01-27 15:36 UTC, timbussmann commented
@tmasternak I reworked the test as discussed this morning, please have another look.

2021-01-27 20:17 UTC, mauroservienti approved these changes

2021-01-28 07:51 UTC, tmasternak approved these changes

2021-01-28 07:51 UTC, merged