Validate if implementation of `ISagaNotFound` isn't a saga type
Particular/NServiceBus pull request #5994
Opened 2021-03-22 17:48 UTC by ramonsmits

2021-03-23 07:12 UTC, SzymonPobiega requested changes

2021-03-23 07:12 UTC, SzymonPobiega commented on src/NServiceBus.Core/Sagas/InvokeSagaNotFoundBehavior.cs
> +                    throw new InvalidOperationException("It is not allowed to inherit `IHandleSagaNotFound` on a Saga type.");
```suggestion
                    throw new InvalidOperationException("Saga types can't implement `IHandleSagaNotFound`. The not found handlers are not bound to a specific saga type and are invoked if none of the sagas mapped to a given message is found.");
```

2021-07-06 09:46 UTC, timbussmann commented
this doesn't seem to target master or a release branch, is that intentional? Given this might be considered a breaking change, is this going into v8?

2021-07-06 15:38 UTC, ramonsmits commented
@timbussmann Yes, I consider this a breaking behavior change to prevent user error that would assuming behavior on a specific saga type only.

Not entirely sure about the branches. I'll need to look into that as can't remember after almost 4mo.

2021-09-11 20:28 UTC, closed without merging