CriticalError.Raise allow null exception
Particular/NServiceBus pull request #6056
Opened 2021-05-11 10:10 UTC by ramonsmits

The current API assumes there is always an exception. If a critical error is not trigger based on an exception then we should be able to invoke a critical error raise too.

For example, raising a critical based on a timer.

Currently requires passing `new Exception()` which feels wrong.

2021-05-12 05:45 UTC, ramonsmits commented on src/NServiceBus.Core/CriticalError/CriticalError.cs
> +
```suggestion

```

2021-05-12 05:45 UTC, ramonsmits commented on src/NServiceBus.Core/CriticalError/CriticalError.cs
> +
```suggestion

```

2021-07-15 12:06 UTC, ramonsmits commented
Requested review on Slack #nservicebus

2021-07-15 12:48 UTC, timbussmann requested changes
RaiseForEndpoint creates a `CriticalErrorContext` that [requires exception to not be null ](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/CriticalError/CriticalErrorContext.cs#L22) so this would currently fail to run.

2021-07-15 13:58 UTC, SeanFeldman commented on src/NServiceBus.Core/CriticalError/CriticalError.cs
> +        public virtual void Raise(string errorMessage, Exception exception = null, CancellationToken cancellationToken = default)
Any specific reason you're not using `=default`?

2021-07-28 15:44 UTC, ramonsmits commented on src/NServiceBus.Core/CriticalError/CriticalError.cs
> +        public virtual void Raise(string errorMessage, Exception exception = null, CancellationToken cancellationToken = default)
```suggestion
        public virtual void Raise(string errorMessage, Exception exception = default, CancellationToken cancellationToken = default)
```

2021-07-28 15:52 UTC, ramonsmits commented
> RaiseForEndpoint creates a `CriticalErrorContext` that [requires exception to not be null ](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/CriticalError/CriticalErrorContext.cs#L22) so this would currently fail to run.

That is unfortunate and seems like a reason to enforce passing an exception object as I do think it makes sense for callbacks to assume that it not null.


Alternatively, it could be an overload as `public virtual void Raise(string errorMessage, string reason, CancellationToken cancellationToken = default)` which could do a `new Exception(reason)` but to satisfy that requirement but not worth having such a API or an extension method.

Thanks for that @timbussmann, based on the breaking behavior I understand the requirement for the exception.

2021-07-28 15:52 UTC, closed without merging