Adds a test that verifies duplicate usage of UseTransport is allowed …
Particular/NServiceBus pull request #6671
Opened 2023-01-16 10:13 UTC by SzymonPobiega

…and last one wins

2023-01-16 10:15 UTC, SzymonPobiega commented
@andreasohlund I am pulling you in because we investigated the issues around `UseTransport` in the functions together. The PRs @mikeminutillo has crafted:

- https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/pull/255
- https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/614

depend on the ability to replace the transport _last minute_ before starting the endpoint and this test needs to be in the core to make sure we don't break that (e.g. by adding a validation that throws when trying to call `UseTransport` the second time)

2023-01-17 07:37 UTC, andreasohlund requested changes
I think we can simplify the test, see https://github.com/Particular/NServiceBus/pull/6672

2023-01-17 08:56 UTC, andreasohlund approved these changes

2023-01-18 05:55 UTC, mikeminutillo approved these changes
This ensures that the second configured transport runs, but it doesn't ensure that the first one doesn't. Both are requirements for the Serverless implmentation.

2023-01-18 10:40 UTC, SzymonPobiega commented
@mikeminutillo I managed to get that unit test working. I think it is better because a) it is a unit test b) it covers both cases you mentioned. @andreasohlund please re-review ;-)

2023-01-19 03:40 UTC, mikeminutillo approved these changes

2023-01-19 06:26 UTC, andreasohlund commented on src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
> +            processingContext.Set("MessageFilePath", transaction.FileToProcess);
This is no longer needed

2023-01-19 07:19 UTC, mikeminutillo commented on src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
> +            processingContext.Set("MessageFilePath", transaction.FileToProcess);
I'll remove it

2023-01-19 07:37 UTC, andreasohlund approved these changes

2023-01-19 07:43 UTC, merged